require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'CODEOWNERS'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/NestedGroups:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/DescribeClass:
  Exclude:
    - spec/integration/**/*_spec.rb

Naming/FileName:
  Exclude: ['lib/rate-limit.rb']
